### ISSUE TITLE
Array length function in VM

### ISSUE THREAD

**Issue by CobrasCobras** [fetchai/ledger#1060]
There is no way of iterating an array without knowing its length, which ends up with duplicate hard-coded values in Etch code. E.g.,

```
var myArray = Array<Int32>(5);
myArray[0] = 3;
myArray[1] = 1;
myArray[2] = 4;
myArray[3] = 1;
// wish I could do: for (I in 0:myArray.length()), for example
for (i in 0:3)
        printLn(toString(myArray[i]));
    endfor
```

**Comment by wkaluza** [comment]
Arrays have a `count()` member function which returns the number of elements.

**Comment by wkaluza** [comment]
Closing, as functionality already exists. The question remains whether we should come up with a more intuitive name than `count`. Other languages seem to lean towards `length`, with `size` being a close second. The problem with `size` is that the term is overloaded to also mean 'size in bytes' rather than 'number of elements'.
