### ISSUE TITLE
Flakey ledger chaincode test CheckBasicTokenContract

### ISSUE THREAD

**Issue by wkaluza** [fetchai/ledger#1216]
This failure was observed on Clang 6 Debug; on replaying the build, the test passed.
```
[ RUN      ] SmartContractTests.CheckBasicTokenContract

/root/workspace/ledger_PR-1108-head/libs/ledger/tests/chaincode/smart_contract_tests.cpp:78: Failure
Expected equality of these values:
  SmartContract::Status::OK
    Which is: 4-byte object <00-00 00-00>
  SendQuery(query_method_name, request, response)
    Which is: 4-byte object <01-00 00-00>

unknown file: Failure
C++ exception with description "Unable to access keys of non-object variant" thrown in the test body.

/root/workspace/ledger_PR-1108-head/libs/ledger/tests/chaincode/smart_contract_tests.cpp:351: Failure
Actual function call count doesn't match EXPECT_CALL(*storage_, Get(target_resource))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
[  FAILED  ] SmartContractTests.CheckBasicTokenContract (10 ms)
```

**Comment by pbukva** [comment]
Actual root cause of this issue is bug in the `fetch::byte_array::FromBase58(...)` function, which allows to iterate the input buffer beyond its end boundary, what occurs in following two scenarios:

- when memory immediately after the buffer end boundary is filled with continuous sequence of _space_ character(s) (one or more). Besides accessing memory beyond end boundary, this leads to returning empty byte array as result.

- when *whole* buffer is filled with  _1_ characters (ascii hex value `0x31`) **AND** memory immediately after the buffer end boundary continues to be filled with continuous sequence of _1_ character(s) (one or more). Besides accessing memory beyond end boundary, this ultimately leads to `std::bad_alloc` exception.
