### ISSUE TITLE
Improve Remove Block Performance

### ISSUE THREAD

**Issue by ejfitzgerald** [fetchai/ledger#666]
The current block removal implementation suffers from poor performance

**Comment by n-hutton** [comment]
I would suggest the following:

Write a benchmark that tests the function ```   bool        RemoveBlock(BlockHash hash) ``` of main_chain.hpp/cpp - probably best to use the in memory only mode (no writing to disk)

There are already a few benchmarks for the main chain in ``` ~/repos/fetch-ledger/libs/ledger/benchmark/main_chain_benchs.cpp ```

This will probably have O(N^2) performance or something like that.

Review the internal workings of mainchain, and rewrite the remove algorithm to be less ugly (Ed wrote it :) )

Hints:

The way the main chain works is that it keeps track of all known blocks and tries to link them back to genesis. It attempts to know the 'heaviest' valid chain (where to be valid it must connect to genesis). When file writing is enabled, it writes blocks that are almost certain into the object store (almost certain is block head - confirmation blocks, in bitcoin this would be 6 blocks).

Occasionally, the block coordinator realises that it needs to remove a block - perhaps it can't find a TX that the block references. The removal of this block will neccessarily cause all of the blocks upwards from that to become 'loose' (not connected to genesis). Since those blocks are a hashed linked list, they should also be removed (not sure if that happens or not).
