### ISSUE TITLE
Transaction sync fixes

### ISSUE THREAD

**Issue by wkaluza** [fetchai/ledger#873]
Transaction syncing fails when attempting to cache transactions. Re-enable caching and rewrite syncing algorithm to improve performance.

**Comment by n-hutton** [comment]
This bug can be replicated in the following way:

check out fetch-ledger nhutton fork:

nathan/bug/transaction_sync_cache

check out ledger-api-py nhutton fork (https://github.com/n-hutton/ledger-api-py/):

nathan/bug/transaction_sync_cache

https://github.com/n-hutton/ledger-api-py/

Build constellation.

In one folder, start a constellation node:

```
rm *.db; ./constellation -port 8000 -lanes 1 -standalone -block-interval 1000
```

Wait until it is mining blocks. 

Send TXs to the node using the ledger api (this needs installing, use the README for this)

```
python3 ./examples/send_transactions_in_bulk.py
```

Once they are sent and executed, start the second node (in a different folder):

```
rm *.db; ./constellation -port 8020 -lanes 1 -peers tcp://127.0.0.1:8001
```

You should see the message being printed by the first node: ``` [ 2019-04-17 00:15:22.527, #10 WARN  :             ObjectStoreSyncProtocol ] Returning object count of: 0 ``` which is incorrect. This behaviour appears to have either been fixed or hidden in subsequent commits, so the file libs/storage/include/storage/transient_object_store.hpp has been cherry picked from the time the bug was first seen. This file appears to cause it.

The transient object store acts as a wrapper around the object store and holds recent transactions in a buffer - ed wrote this I believe.

Note, the way I would probably debug this is using breakpoints in clion and stepping through the code. If you do this, clion will build constellation in debug mode which changes mutexes in the code to a mutex that will SIGKILL if it's locked for too long (a useful thing to find in debug mode). To disable this so it doesn't trigger during stepping through code, change the following in mutex.hpp: 

```
#ifdef NDEBUG
using Mutex = ProductionMutex;
#else
using Mutex = ProductionMutex;
#endif
```
