### ISSUE TITLE
Implement methods to expose node members (e.g. Weights/bias etc.) via graph interface.

### ISSUE THREAD

**Issue by juergendkeba** [fetchai/ledger#936]
In order to easily share weights among nodes in the computational graph, it would be desirable to add a `GetWeights()` (or something similar) method to the `NodeInterface`. 

Then, the following would be accomplished quite easily
``
g.AddNode<fetch::ml::ops::Embeddings<ArrayType>>("el1", {"input_el1"}, VOCAB_SIZE, EMBEDDING_SIZE);
 g.AddNode<fetch::ml::ops::Embeddings<ArrayType>>("el2", {"input_el2"}, g.GetNode("el1")->GetWeights());
``

**Comment by pierre-wilmot-fetch-ai** [comment]
GetWeights doesn't really belong in NodeInterface since not every node is encapsulating an ops with weights. For example calling GetWeights on a Node\<Relu\> makes no sense.
We could try to add it in the Trainable interface (defined in ml/ops/weights.hpp), but the problem is that once things are wrapped into a node that itself gets wrapped into a graph, it become impossible to retrieve the actual object without a lot of ugly casting.

In the situation of weight sharing, you know about it from the begingin, so just allocate your weight tensor beforehand and do :
 
```
std::shared_ptr<...> w = Tensor({VOCAB_SIZE, EMBEDDING_SIZE});
g.AddNode<fetch::ml::ops::Embeddings<ArrayType>>("el1", {"input_el1"}, w); 
g.AddNode<fetch::ml::ops::Embeddings<ArrayType>>("el2", {"input_el2"}, w);
```

**Comment by baykaner** [comment]
I think in this case the weights sharing isn't the difficult part, it's the extraction of those weights later; If a user is making a big and complicated graph it shouldn't be their responsibility to manually define and pass in all the weight matrices.

It's true that it takes a lot of ugly casting at the moment; but that just means we need to wrap up that ugly casting in elegant graph methods that let a user ask for node members. One way would be as suggested, to have something like a GetWeights() in NodeInterface, but that has the downside of requiring to tell the user to stop being silly if they ask for the weights from a node that doesn't have anything called weights. Another option would be to have a more generic Expose() kind of method that returns a vector of tensors constituting all the node members that are allowed to be exposed (e.g. {} for Relu, or {Weights} for weights, and {Weights, Bias} for fully_connected_layer). I'm sure we can think of other options too; but we do need to solve this issue of elegantly giving access to node members.

I'm going to re-open and rename the issue as such.
